databases:
  - name: budget-app
    databaseName: budget_db_mv8u
    user: budget_users

services:
  - type: web
    name: bloggy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_db_mv8u
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false