databases:
  - name: blog-app
    databaseName: blogdb
    user: blog_users

services:
  - type: web
    name: bloggy
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: blogdb
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false